var topics = [
    // Colours
    {
        key: "colours",
        values: [
            "Red",
            "Blue",
            "Green",
            "Yellow",
            "Black",
            "White",
            "Orange",
            "Pink",
            "Brown",
            "Purple",
            "Gray",
            "Gold",
            "Silver",
            "Bronze",
            "Rainbow",
            "Cream",
            "Turquoise",
            "Lilac",
            "Magenta",
            "Cyan",
            "Maroon",
            "Navy",
            "Olive",
            "Teal",
        ]
    },
    // Food
    {
        key: "food",
        values: [
            "Curry",
            "Chips",
            "Salad",
            "Fish",
            "Chicken",
            "Sausage",
            "Orange",
            "Mango",
            "Leek",
            "Tomato",
            "Pepper",
            "Chilli",
            "Beef",
            "Pizza",
            "Pasta",
            "Ice cream",
            "Chocolate",
            "Strawberries",
            "Rice",
            "Bread",
            "Cheese",
            "Eggs",
            "Soup",
            "Sandwich",
            "Burger",
            "Fries",
            "Tacos",
            "Noodles",
            "Dumplings",
            "Sushi",
            "Ramen",
            "Pancakes",
            "Oatmeal",
            "Cereal",
            "Yogurt",
            "Milk",
            "Apple",
            "Banana",
            "Grapes",
            "Avocado",
            "Broccoli",
            "Carrot",
            "Potato",
            "Onion",
            "Mushroom",
            "Spinach",
            "Beans",
            "Lentils",
            "Tofu",
            "Tempeh",
            "Hummus",
            "Falafel",
            "Baklava",
            "Donut",
            "Bagel",
            "Pretzel",
            "Popcorn",
            "Nuts",
            "Granola",
        ]
    },
    // Capitals
    {
        key: "capitals",
        values: [
            "London",
            "Moscow",
            "Paris",
            "Berlin",
            "Madrid",
            "Rome",
            "Cairo",
            "Helsinki",
            "Stockholm",
            "Oslo",
            "Washington",
            "Mexico City",
            "Beijing",
            "Tokyo",
            "Seoul",
            "Vienna",
            "Nairobi",
            "Marrakesh",
            "New Delhi",
            "Jakarta",
            "Bangkok",
            "Buenos Aires",
            "Brasilia",
            "Ottawa",
            "Canberra"
        ]
    },
    // Rooms
    {
        key: "rooms",
        values: [
            "Hallway",
            "Kitchen",
            "Dining room",
            "Lounge",
            "Bathroom",
            "Bedroom",
            "Cellar",
            "Attic",
            "Dungeon",
            "Conservatory",
            "Shed",
            "Study",
            "Garage",
            "Music room",
            "Workshop",
            "Greenhouse",
            "Gym",
            "Studio",
            "Living room",
            "Office",
            "Laundry room",
            "Game room",
            "Library",
            "Sunroom",
            "Pantry",
            "Mudroom",
            "Balcony",
            "Basement",
            "Theater room",
            "Walk-in closet"
        ]
    },
    // Pets
    {
        key: "pets",
        values: [
            "Dog",
            "Cat",
            "Parrot",
            "Rabbit",
            "Hamster",
            "Guinea pig",
            "Goldfish",
            "Snake",
            "Lizard",
            "Horse",
            "Alpaca",
            "Frog",
            "Rat",
            "Crab",
            "Budgie",
            "Spider",
            "Donkey",
            "Owl",
            "Turtle",
            "Ferret",
            "Hedgehog",
            "Gecko",
            "Iguana",
        ]
    },
    // Harry Potter
    {
        key: "harry potter",
        values: [
            "Harry Potter",
            "Ron Weasley",
            "Hermione Granger",
            "Neville Longbottom",
            "Luna Lovegood",
            "Albus Dumbledore",
            "Minerva McGonagall",
            "Pomona Sprout",
            "Severus Snape",
            "Filius Flitwick",
            "Sirius Black",
            "Remus Lupin",
            "Peter Pettigrew",
            "Lord Voldemort",
            "Draco Malfoy",
            "Rubeus Hagrid",
            "Dobby",
            "Argus Filch"
        ]
    },
    // Marvel Heroes
    {
        key: "marvel heroes",
        values: [
            "Spiderman",
            "Ironman",
            "Hulk",
            "Captain America",
            "Thor",
            "Deadpool",
            "Wolverine",
            "Groot",
            "Loki",
            "Star-lord",
            "Gamora",
            "Drax",
            "Magneto",
            "Jessica Jones",
            "Daredevil",
            "Charles Xavier",
            "Ant-Man",
            "Luke Cage"
        ]
    },
    // Disney
    {
        key: "disney",
        values: [
            "Cinderella",
            "Belle",
            "Snow White",
            "Ariel",
            "Mulan",
            "Jasmine",
            "Pocahontas",
            "Mickey Mouse",
            "Donald Duck",
            "Pluto",
            "Bambi",
            "Peter Pan",
            "Captain Hook",
            "Baloo",
            "Winnie the Pooh",
            "Aladdin",
            "Hercules",
            "Tarzan"
        ]
    },
    // Sea Creatures
    {
        key: "sea creatures",
        values: [
            "Starfish",
            "Shark",
            "Whale",
            "Dolphin",
            "Cod",
            "Jellyfish",
            "Seahorse",
            "Puffer fish",
            "Orca",
            "Coral",
            "Oysters",
            "Mussels",
            "Octopus",
            "Kraken",
            "Turtle",
            "Seal",
            "Sea cucumber",
            "Stingray"
        ]
    },
    // Sports
    {
        key: "sports",
        values: [
            "Football",
            "Rugby",
            "Athletics",
            "Swimming",
            "Hockey",
            "Tennis",
            "Badminton",
            "Golf",
            "Squash",
            "Gymnastics",
            "Trampolining",
            "Cycling",
            "Volleyball",
            "Cricket",
            "Baseball",
            "Basketball",
            "Skiing",
            "Sailing"
        ]
    },
    // Hobbies
    {
        key: "hobbies",
        values: [
            "Stamps",
            "Trains",
            "Model Making",
            "Knitting",
            "Fishing",
            "Reading",
            "Painting",
            "Gardening",
            "Sailing",
            "Travel",
            "Walking",
            "Pottery",
            "Cooking",
            "Yoga",
            "Photography",
            "Hiking",
            "Bird watching",
            "Singing"
        ]
    },
    // School
    {
        key: "school",
        values: [
            "Maths",
            "Chemistry",
            "Physics",
            "Biology",
            "History",
            "Philosophy",
            "Geography",
            "English",
            "Economics",
            "French",
            "Art",
            "Music",
            "Physical education",
            "Latin",
            "Religious studies",
            "Technology",
            "Geology",
            "Drama"
        ]
    },
    // Transport
    {
        key: "transport",
        values: [
            "Plane",
            "Car",
            "Tank",
            "Helicopter",
            "Cruise ship",
            "Hovercraft",
            "Motorbike",
            "Bus",
            "Segway",
            "Cable car",
            "Jet ski",
            "Hot air balloon",
            "Train",
            "Spaceship",
            "Magic carpet",
            "Broomstick",
            "Cycle",
            "Skateboard"
        ]
    },
    // Jobs
    {
        key: "jobs",
        values: [
            "Fisherman",
            "Lumberjack",
            "Nurse",
            "Waiter",
            "Lighthouse keeper",
            "Secretary",
            "Accountant",
            "Teacher",
            "Lorry driver",
            "Security guard",
            "Chef",
            "Architect",
            "Police officer",
            "Lawyer",
            "Carpenter",
            "Butcher",
            "Doctor",
            "Film director"
        ]
    },
    // Civilizations
    {
        key: "civilizations",
        values: [
            'Romans',
            'Egyptians',
            'Mayans',
            'Mongols',
            'Aztecs',
            'Japanese',
            'Persians',
            'Greeks',
            'Turks',
            'Vikings',
            'Incas',
            'Spanish',
            'Zulu',
            'Chinese',
            'Spartans',
            'Aliens',
            'Eskimos',
            'Samurai'
        ]
    },
    // Tattoos
    {
        key: "tattoos",
        values: [
            'Stars',
            'Angel',
            'Wings',
            'Dragon',
            'Eagle',
            'Fairy',
            'Heart',
            'Skull',
            'Sword',
            'Tiger',
            'Swallows',
            'Flower',
            'Butterfly',
            'Cross',
            'Owl',
            'Anchor',
            'Whale',
            'Lightning'
        ]
    },
    // Geography
    {
        key: "geography",
        values: [
            'Lake',
            'Sea',
            'Valley',
            'Mountain',
            'River',
            'Desert',
            'Ocean',
            'Forest',
            'Jungle',
            'Island',
            'Glacier',
            'Waterfall',
            'Volcano',
            'Cave',
            'Arctic',
            'Swamp',
            'Gorge',
            'Reef'
        ]
    },
    // Movies
    {
        key: "movies",
        values: [
            "The Shawshank Redemption",
            "The Godfather",
            "Pulp Fiction",
            "Forrest Gump",
            "Schindler's List",
            "Inception",
            "The Matrix",
            "Fight Club",
            "Titanic",
            "Jurassic Park",
            "Star Wars: Episode IV - A New Hope",
            "The Lord of the Rings: The Fellowship of the Ring",
            "The Avengers",
            "Avatar",
            "The Lion King",
            "The Silence of the Lambs",
            "Back to the Future",
        ]
    },
    // Books
    {
        key: "books",
        values: [
            "The Bible",
            "1984 by George Orwell",
            "The Great Gatsby by F. Scott Fitzgerald",
            "The Lord of the Rings by J.R.R. Tolkien",
            "Harry Potter and the Philosopher's Stone by J.K. Rowling",
            "The Quran",
            "Pride and Prejudice by Jane Austen",
            "The Hobbit by J.R.R. Tolkien",
            "The Chronicles of Narnia by C.S. Lewis",
            "The Hunger Games by Suzanne Collins",
            "The Da Vinci Code by Dan Brown",
            "The Torah",
            "The Hitchhiker's Guide to the Galaxy by Douglas Adams",
            "Moby-Dick by Herman Melville",
            "War and Peace by Leo Tolstoy",
            "Don Quixote by Miguel de Cervantes",
            "The Girl with the Dragon Tattoo by Stieg Larsson",
            "The Art of War by Sun Tzu",
            "Alice's Adventures in Wonderland by Lewis Carroll",
            "The Diary of a Young Girl by Anne Frank",
            "The Communist Manifesto by Karl Marx"
        ]
    },
    // Music Genres
    {
        key: "music genres",
        values: [
            "Pop",
            "Rock",
            "Hip Hop",
            "Jazz",
            "Classical",
            "Country",
            "Electronic",
            "R&B",
            "Reggae",
            "Metal",
            "Indie",
            "Folk",
            "Blues",
            "Alternative",
            "Latin"
        ]
    },

    // Technology Gadgets
    {
        key: "technology gadgets",
        values: [
            "Smartphone",
            "Laptop",
            "Tablet",
            "Smartwatch",
            "Fitness Tracker",
            "Headphones",
            "Camera",
            "Drone",
            "VR Headset",
            "Gaming Console",
            "Smart Home Device",
            "E-reader",
            "Fitness Equipment"
        ]
    },

    // Famous Landmarks
    {
        key: "landmarks",
        values: [
            "Eiffel Tower",
            "Statue of Liberty",
            "Great Wall of China",
            "Pyramids of Giza",
            "Taj Mahal",
            "Machu Picchu",
            "Colosseum",
            "Sydney Opera House",
            "Big Ben",
            "Petra",
            "Mount Rushmore",
            "Acropolis",
            "Sphinx",
            "Golden Gate Bridge"
        ]
    }
];

module.exports = topics;
